In [5]:
import pandas as pd 
import sklearn
import numpy 
import matplotlib
import seaborn

In [2]:
!pip install scikit-learn
!pip install seaborn


[notice] A new release of pip available: 22.3 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


     ------------------------------------ 294.9/294.9 kB 253.0 kB/s eta 0:00:00



[notice] A new release of pip available: 22.3 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
data = pd.read_csv("Hotel Reservations.csv")
data.duplicated().sum()

0

In [7]:
data.isnull().sum()

Booking_ID                              0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

In [23]:
data.dtypes

Booking_ID                               object
no_of_adults                              int64
no_of_children                            int64
no_of_weekend_nights                      int64
no_of_week_nights                         int64
type_of_meal_plan                        object
required_car_parking_space                int64
room_type_reserved                       object
lead_time                                 int64
arrival_year                              int64
arrival_month                             int64
arrival_date                              int64
market_segment_type                      object
repeated_guest                            int64
no_of_previous_cancellations              int64
no_of_previous_bookings_not_canceled      int64
avg_price_per_room                      float64
no_of_special_requests                    int64
booking_status                           object
dtype: object

In [24]:
type(data)


pandas.core.frame.DataFrame

In [25]:
data.head()

Booking_ID  no_of_adults  no_of_children  no_of_weekend_nights  \
0   INN00001             2               0                     1   
1   INN00002             2               0                     2   
2   INN00003             1               0                     2   
3   INN00004             2               0                     0   
4   INN00005             2               0                     1   

   no_of_week_nights type_of_meal_plan  required_car_parking_space  \
0                  2       Meal Plan 1                           0   
1                  3      Not Selected                           0   
2                  1       Meal Plan 1                           0   
3                  2       Meal Plan 1                           0   
4                  1      Not Selected                           0   

  room_type_reserved  lead_time  arrival_year  arrival_month  arrival_date  \
0        Room_Type 1        224          2017             10             2   
1        Room_Type 1          5          2018             11             6   
2        Room_Type 1          1          2018              2            28   
3        Room_Type 1        211          2018              5            20   
4        Room_Type 1         48          2018              4            11   

  market_segment_type  repeated_guest  no_of_previous_cancellations  \
0             Offline               0                             0   
1              Online               0                             0   
2              Online               0                             0   
3              Online               0                             0   
4              Online               0                             0   

   no_of_previous_bookings_not_canceled  avg_price_per_room  \
0                                     0               65.00   
1                                     0              106.68   
2                                     0               60.00   
3                                     0              100.00   
4                                     0               94.50   

   no_of_special_requests booking_status  
0                       0   Not_Canceled  
1                       1   Not_Canceled  
2                       0       Canceled  
3                       0       Canceled  
4                       0       Canceled

In [8]:

data = data.drop('Booking_ID',axis=1)


In [27]:
data.head()

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
0             2               0                     1                  2   
1             2               0                     2                  3   
2             1               0                     2                  1   
3             2               0                     0                  2   
4             2               0                     1                  1   

  type_of_meal_plan  required_car_parking_space room_type_reserved  lead_time  \
0       Meal Plan 1                           0        Room_Type 1        224   
1      Not Selected                           0        Room_Type 1          5   
2       Meal Plan 1                           0        Room_Type 1          1   
3       Meal Plan 1                           0        Room_Type 1        211   
4      Not Selected                           0        Room_Type 1         48   

   arrival_year  arrival_month  arrival_date market_segment_type  \
0          2017             10             2             Offline   
1          2018             11             6              Online   
2          2018              2            28              Online   
3          2018              5            20              Online   
4          2018              4            11              Online   

   repeated_guest  no_of_previous_cancellations  \
0               0                             0   
1               0                             0   
2               0                             0   
3               0                             0   
4               0                             0   

   no_of_previous_bookings_not_canceled  avg_price_per_room  \
0                                     0               65.00   
1                                     0              106.68   
2                                     0               60.00   
3                                     0              100.00   
4                                     0               94.50   

   no_of_special_requests booking_status  
0                       0   Not_Canceled  
1                       1   Not_Canceled  
2                       0       Canceled  
3                       0       Canceled  
4                       0       Canceled

In [9]:
data = data.sort_values(by=['arrival_year', 'arrival_month', 'arrival_date']).reset_index(drop=True)
split_index = round(len(data) * 0.8)
train = data.iloc[:split_index]
test = data.iloc[split_index:]

In [32]:
type(train)
train.head()

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
0             1               0                     0                  2   
1             2               0                     0                  2   
2             2               0                     0                  2   
3             2               0                     0                  2   
4             1               0                     0                  4   

  type_of_meal_plan  required_car_parking_space room_type_reserved  lead_time  \
0       Meal Plan 2                           0        Room_Type 1        257   
1       Meal Plan 2                           0        Room_Type 1        257   
2       Meal Plan 2                           0        Room_Type 1        257   
3       Meal Plan 2                           0        Room_Type 1        257   
4       Meal Plan 1                           0        Room_Type 1         65   

   arrival_year  arrival_month  arrival_date market_segment_type  \
0          2017              7             1             Offline   
1          2017              7             1              Online   
2          2017              7             1              Online   
3          2017              7             1              Online   
4          2017              7             1              Online   

   repeated_guest  no_of_previous_cancellations  \
0               0                             0   
1               0                             0   
2               0                             0   
3               0                             0   
4               0                             0   

   no_of_previous_bookings_not_canceled  avg_price_per_room  \
0                                     0                80.0   
1                                     0               101.5   
2                                     0               101.5   
3                                     0               101.5   
4                                     0                68.0   

   no_of_special_requests booking_status  
0                       0   Not_Canceled  
1                       0       Canceled  
2                       0       Canceled  
3                       0       Canceled  
4                       1       Canceled

In [10]:
x_train = train.drop('booking_status', axis=1)
y_train = train['booking_status']

print(x_train.head())
print(y_train.head())

   no_of_adults  no_of_children  ...  avg_price_per_room  no_of_special_requests
0             1               0  ...                80.0                       0
1             2               0  ...               101.5                       0
2             2               0  ...               101.5                       0
3             2               0  ...               101.5                       0
4             1               0  ...                68.0                       1

[5 rows x 17 columns]
0    Not_Canceled
1        Canceled
2        Canceled
3        Canceled
4        Canceled
Name: booking_status, dtype: object


In [11]:
x_test = test.drop('booking_status', axis=1)
y_test = test['booking_status']

print(x_test.head())
print()
y_test.head()

       no_of_adults  no_of_children  ...  avg_price_per_room  no_of_special_requests
29020             2               2  ...              190.80                       0
29021             2               0  ...               97.02                       0
29022             2               0  ...              157.50                       2
29023             1               0  ...              125.00                       0
29024             1               0  ...              132.30                       0

[5 rows x 17 columns]



29020        Canceled
29021        Canceled
29022    Not_Canceled
29023    Not_Canceled
29024        Canceled
Name: booking_status, dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)
le.classes_
y_test = le.fit_transform(y_test)
le.classes_

array(['Canceled', 'Not_Canceled'], dtype=object)

In [13]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

num_cols = ['lead_time', 'avg_price_per_room']
cat_cols = ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(drop='first'), cat_cols)
    ],
    remainder='passthrough'
)

# Fit only on training set
x_train = preprocessor.fit_transform(x_train)

# Apply the same fitted transformation to test set
x_test = preprocessor.transform(x_test)

In [14]:
from sklearn.linear_model import LogisticRegression
#intialize the model
model = LogisticRegression(solver='liblinear',random_state=42)


In [15]:
#Train the model
model.fit(x_train,y_train)

LogisticRegression(random_state=42, solver='liblinear')

In [22]:
#Make Predictions
y_pred_test = model.predict(x_test)
y_pred_train = model.predict(x_train)

In [25]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#Check accuracy 
print("Test Accuracy:", accuracy_score(y_test,y_pred_test))

#Detailed report
print("Test Classification Report:\n", classification_report(y_test, y_pred_test))

#Confution Matrix
print("Test Confution Matrix:\n", confusion_matrix(y_test,y_pred_test))
print()
#Check accuracy 
print("Train Accuracy:", accuracy_score(y_train,y_pred_train))

#Detailed report
print("Train Classification Report:\n", classification_report(y_train, y_pred_train))

#Confution Matrix
print("Train Confution Matrix:\n", confusion_matrix(y_train,y_pred_train))

Test Accuracy: 0.7931082012405237
Test Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.57      0.66      2508
           1       0.80      0.91      0.85      4747

    accuracy                           0.79      7255
   macro avg       0.79      0.74      0.75      7255
weighted avg       0.79      0.79      0.78      7255

Test Confution Matrix:
 [[1429 1079]
 [ 422 4325]]

Train Accuracy: 0.8044452101998621
Train Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.62      0.67      9377
           1       0.83      0.89      0.86     19643

    accuracy                           0.80     29020
   macro avg       0.78      0.76      0.77     29020
weighted avg       0.80      0.80      0.80     29020

Train Confution Matrix:
 [[ 5814  3563]
 [ 2112 17531]]


In [28]:
from sklearn.model_selection import GridSearchCV

#Define the grid of parameters
param_grid = { 
    'C': [0.01,0.1,1,10],
    'solver': ['liblinear', 'lbfgs']
}

#setup GridSerachCV
grid_search = GridSearchCV(LogisticRegression(random_state=4), param_grid, cv =5)
grid_search.fit(x_train,y_train)

#Best parameters
print('Best Parameters:', grid_search.best_params_)

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-

Best Parameters: {'C': 1, 'solver': 'lbfgs'}


c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [29]:
best_model= grid_search.best_estimator_

y_pr_test = best_model.predict(x_test)
y_pr_train = best_model.predict(x_train)

In [30]:
#Check accuracy 
print("Test Accuracy:", accuracy_score(y_test,y_pr_test))

#Detailed report
print("Test Classification Report:\n", classification_report(y_test, y_pr_test))

#Confution Matrix
print("Test Confution Matrix:\n", confusion_matrix(y_test,y_pr_test))
print()
#Check accuracy 
print("Train Accuracy:", accuracy_score(y_train,y_pr_train))

#Detailed report
print("Train Classification Report:\n", classification_report(y_train, y_pr_train))

#Confution Matrix
print("Train Confution Matrix:\n", confusion_matrix(y_train,y_pr_train))

Test Accuracy: 0.7875947622329428
Test Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.55      0.64      2508
           1       0.79      0.91      0.85      4747

    accuracy                           0.79      7255
   macro avg       0.78      0.73      0.75      7255
weighted avg       0.78      0.79      0.78      7255

Test Confution Matrix:
 [[1391 1117]
 [ 424 4323]]

Train Accuracy: 0.8017918676774638
Train Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.61      0.67      9377
           1       0.83      0.89      0.86     19643

    accuracy                           0.80     29020
   macro avg       0.78      0.75      0.76     29020
weighted avg       0.80      0.80      0.80     29020

Train Confution Matrix:
 [[ 5725  3652]
 [ 2100 17543]]


In [31]:
model = LogisticRegression(class_weight='balanced',random_state=42)
model.fit(x_train,y_train)

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(class_weight='balanced', random_state=42)

In [32]:
#Make Predictions
y_pred_test = model.predict(x_test)
y_pred_train = model.predict(x_train)

In [33]:
#Check accuracy 
print("Test Accuracy:", accuracy_score(y_test,y_pred_test))

#Detailed report
print("Test Classification Report:\n", classification_report(y_test, y_pred_test))

#Confution Matrix
print("Test Confution Matrix:\n", confusion_matrix(y_test,y_pred_test))
print()
#Check accuracy 
print("Train Accuracy:", accuracy_score(y_train,y_pred_train))

#Detailed report
print("Train Classification Report:\n", classification_report(y_train, y_pred_train))

#Confution Matrix
print("Train Confution Matrix:\n", confusion_matrix(y_train,y_pred_train))

Test Accuracy: 0.8006891798759477
Test Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.69      0.71      2508
           1       0.84      0.86      0.85      4747

    accuracy                           0.80      7255
   macro avg       0.78      0.78      0.78      7255
weighted avg       0.80      0.80      0.80      7255

Test Confution Matrix:
 [[1737  771]
 [ 675 4072]]

Train Accuracy: 0.7732942798070296
Train Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.78      0.69      9377
           1       0.88      0.77      0.82     19643

    accuracy                           0.77     29020
   macro avg       0.75      0.77      0.76     29020
weighted avg       0.79      0.77      0.78     29020

Train Confution Matrix:
 [[ 7294  2083]
 [ 4496 15147]]
